### ISSUE TITLE
Unable to select date in the past

### ISSUE THREAD

**Issue by thisoldbear** [reecelucas/react-datepicker#1]
Hey @reecelucas. Looking at `dateIsSelectable()` in `helpers/date.js`, am I right in assuming you can't select a day that is in the past? 

Combinations of `initialDate`,  `minDate` and `maxDate` don't seem to allow it either.

**Comment by reecelucas** [comment]
Hi @thisoldbear,

This should be fixed in v2.0.0, thanks to @Malven . Past dates are now selectable by default.  The `minDate` prop can be used to override this behaviour. Hope this helps!
